//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SlotMachine.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SlotMachineEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SlotMachineEntities object using the connection string found in the 'SlotMachineEntities' section of the application configuration file.
        /// </summary>
        public SlotMachineEntities() : base("name=SlotMachineEntities", "SlotMachineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SlotMachineEntities object.
        /// </summary>
        public SlotMachineEntities(string connectionString) : base(connectionString, "SlotMachineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SlotMachineEntities object.
        /// </summary>
        public SlotMachineEntities(EntityConnection connection) : base(connection, "SlotMachineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AppUser> AppUsers
        {
            get
            {
                if ((_AppUsers == null))
                {
                    _AppUsers = base.CreateObjectSet<AppUser>("AppUsers");
                }
                return _AppUsers;
            }
        }
        private ObjectSet<AppUser> _AppUsers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AppUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAppUsers(AppUser appUser)
        {
            base.AddObject("AppUsers", appUser);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SlotMachineDBModel", Name="AppUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AppUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AppUser object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="facebookId">Initial value of the FacebookId property.</param>
        public static AppUser CreateAppUser(global::System.Int64 id, global::System.Int64 facebookId)
        {
            AppUser appUser = new AppUser();
            appUser.Id = id;
            appUser.FacebookId = facebookId;
            return appUser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FacebookId
        {
            get
            {
                return _FacebookId;
            }
            set
            {
                OnFacebookIdChanging(value);
                ReportPropertyChanging("FacebookId");
                _FacebookId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FacebookId");
                OnFacebookIdChanged();
            }
        }
        private global::System.Int64 _FacebookId;
        partial void OnFacebookIdChanging(global::System.Int64 value);
        partial void OnFacebookIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Points
        {
            get
            {
                return _Points;
            }
            set
            {
                OnPointsChanging(value);
                ReportPropertyChanging("Points");
                _Points = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Points");
                OnPointsChanged();
            }
        }
        private Nullable<global::System.Double> _Points;
        partial void OnPointsChanging(Nullable<global::System.Double> value);
        partial void OnPointsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastVisited
        {
            get
            {
                return _LastVisited;
            }
            set
            {
                OnLastVisitedChanging(value);
                ReportPropertyChanging("LastVisited");
                _LastVisited = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastVisited");
                OnLastVisitedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastVisited;
        partial void OnLastVisitedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastVisitedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TimesPlayed
        {
            get
            {
                return _TimesPlayed;
            }
            set
            {
                OnTimesPlayedChanging(value);
                ReportPropertyChanging("TimesPlayed");
                _TimesPlayed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimesPlayed");
                OnTimesPlayedChanged();
            }
        }
        private Nullable<global::System.Int32> _TimesPlayed;
        partial void OnTimesPlayedChanging(Nullable<global::System.Int32> value);
        partial void OnTimesPlayedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> JackPotCount
        {
            get
            {
                return _JackPotCount;
            }
            set
            {
                OnJackPotCountChanging(value);
                ReportPropertyChanging("JackPotCount");
                _JackPotCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JackPotCount");
                OnJackPotCountChanged();
            }
        }
        private Nullable<global::System.Int32> _JackPotCount;
        partial void OnJackPotCountChanging(Nullable<global::System.Int32> value);
        partial void OnJackPotCountChanged();

        #endregion
    
    }

    #endregion
    
}
